CURRENT_SNAPSHOT_VERSION=`mvn -s d:/Tools/apache-maven-3.5.4/conf/settings.xml -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec`
echo "CURRENT_SNAPSHOT_VERSION=$CURRENT_SNAPSHOT_VERSION"
VERSION_COMPONENTS=${CURRENT_SNAPSHOT_VERSION//[.-]/}
echo "VERSION_COMPONENTS=${VERSION_COMPONENTS[*]}"
RELEASE_VERSION="${VERSION_COMPONENTS[0]}.${VERSION_COMPONENTS[1]}.${VERSION_COMPONENTS[2]}.${VERSION_COMPONENTS[3]}"
echo "aRELEASE_VERSION=$RELEASE_VERSION"